<?php View::content() ?>

<div style="max-width: 500px;">
    <h1><?= isset($Users->id) ? 'Edit User' : 'Create User' ?></h1>
    <?= Form::open("admin/users/" . (isset($Users->id) ? "update/{$Users->id}" : "create"), 'post', ['autocomplete' => 'off']) ?>

    <?php if (isset($Users->id)): ?>
        <?= Form::hidden('id', '', $Users->id) ?>
    <?php endif; ?>

    <label class="required">Email *
    <?= Form::email('Users.email', 'required maxlength=255') ?></label>

    <label>First Name
    <?= Form::text('Users.first_name', 'maxlength=255') ?></label>

    <label>Last Name
    <?= Form::text('Users.last_name', 'maxlength=255') ?></label>

    <button type="submit">
        <?= isset($user->id) ? 'Update' : 'Create' ?>
    </button>
    <?= Form::close() ?>

    <div>
        <a href="../" class="btn btn-default"><?= _('List') ?></a>
    </div>
</div>
